version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Berlin
  reviewers:
  - DAmNRelentless
  assignees:
  - DAmNRelentless
  labels:
  - status > pending
  - type > dependency
  ignore:
  - dependency-name: net.minecraftforge.gradle:ForgeGradle
    versions:
    - 4.0.13
    - 4.0.15
    - 4.0.16
    - 4.0.17
    - 4.0.19
    - 4.0.22
    - 4.0.23
    - 4.1.0
    - 4.1.1
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.1.7
  rebase-strategy: disabled
