name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
          cache: npm

      - name: Setup NPM Cache
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ${{ runner.os }}-npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Check Prettier Format
        run: npx pretty-quick --check --verbose

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube --info

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Checks
        run: ./gradlew check --no-daemon

      - name: Test
        run: ./gradlew test --no-daemon

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: check
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Checks
        run: ./gradlew check --no-daemon

      - name: Test
        run: ./gradlew test --no-daemon

      - name: Assemble
        run: ./gradlew jar --no-daemon

      - name: Find the jar
        run: echo "JAR_FILE=$(find build/libs/extracpus-*-*.jar)" >> $GITHUB_ENV

      - name: Extract Minecraft and Mod Version
        run: echo ${JAR_FILE%.*} | awk -F- '{ print "MINECRAFT_VERSION=" $2; print "MOD_VERSION=" $3; }' >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ExtraCPUs-${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}.jar
          path: ${{ env.JAR_FILE }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.JAR_FILE }}
